name: ig_mean
attributor:
  _target_: motionbench.attribution.captum_methods.IntegratedGradientsAttributor
  baseline: mean
  n_steps: 20
players:
  _target_: motionbench.players.temporal_windows.TemporalWindows
